### ISSUE TITLE
To-Do's

### ISSUE THREAD

**Issue by ryanlapeyre** [ryanlapeyre/CS4330FinalProject#1]
# C#
<strike>Classes.md</strike>
<strike>ErrorAndExceptionHandling.md</strike>
<strike> FunctionalProgramming.md </strike>
<strike>InheritanceOrExtension.md</strike>
<strike>InstanceReference.md</strike>
<strike>InterfacesOrProtocols.md</strike>
<strike>ListenersAndEventHandlers.md</strike>
<strike> MemoryManagement.md </strike>
<strike>Multithreading.md</strike>
<strike>NameSpaces.md</strike>
<strike>NulOrNilReferences.md</strike>
<strike>ProceduralProgramming.md</strike>
<strike>Properties.md</strike>
<strike>Purpose.md</strike>
<strike>Reflection.md</strike>
<strike>Singleton.md</strike>
<strike>Types.md</strike>
<strike>UniqueFeatures.md</strike>

# Ruby
<strike>Classes.md</strike>
<strike>ErrorAndExceptionHandling.md</strike>
<strike>FunctionalProgramming.md</strike>
<strike>InheritanceOrExtension.md</strike>
<strike>InstanceReference.md</strike>
<strike>InterfacesOrProtocols.md</strike>
<strike>ListenersAndEventHandlers.md</strike>
<strike> MemoryManagement.md </strike>
<strike>Multithreading.md</strike>
<strike>NameSpaces.md</strike>
<strike>NulOrNilReferences.md</strike>
<strike>ProceduralProgramming.md</strike>
<strike>Properties.md</strike>
<strike>Purpose.md</strike>
<strike>Reflection.md</strike>
<strike>Singleton.md</strike>
Types.md
<strike>UniqueFeatures.md</strike>

**Comment by not-omer** [comment]
I'll do:

- <strike> Functional programming </strike>
- <strike> Reflection </strike>
- <strike> Multithreading </strike>
- <strike> Memory management </strike>
- <strike> Null references </strike>
- <strike> Types </strike>

**Comment by MasonFlint44** [comment]
I've got:
* <strike>Purpose</strike>
* <strike>Properties</strike>
* <strike>Singleton</strike>
* <strike>Procedural programming</strike>
* <strike>Listeners</strike>
* <strike>Instance reference</strike>

**Comment by not-omer** [comment]
Classes.md
ErrorAndExceptionHandling.md
FunctionalProgramming.md
InheritanceOrExtension.md
InstanceReference.md
InterfacesOrProtocols.md
ListenersAndEventHandlers.md
MemoryManagement.md
Multithreading.md
NameSpaces.md
NulOrNilReferences.md
ProceduralProgramming.md
Properties.md
Purpose.md
README.md
Reflection.md
Singleton.md
Types.md
UniqueFeatures.md

**Comment by ryanlapeyre** [comment]
<strike>- Classes </strike>
<strike>- InterfaceOrProtocols </strike>
<strike>- UniqueFeatures </strike>
<strike>- InheritanceOrExtension</strike>
<strike>- Namespaces </strike>
<strike>- ErrorOrExceptionHandling</strike>
# DONE

**Comment by not-omer** [comment]
![image](https://cloud.githubusercontent.com/assets/8787033/25785961/ee0745a2-3351-11e7-86f4-c4713c42e328.png)

:1st_place_medal:

**Comment by ryanlapeyre** [comment]
lmaoo for a second i thought it was dale commenting his own face

**Comment by not-omer** [comment]
I'm done except for the Ruby part of the Types section, if someone could help me expand on that it would be greatly appreciated 👍 :^)
